version: '2'

services:
  cloudwatch2loggly:
    image: node:8.10-alpine
    command: sh
    working_dir: /usr/share/app
    volumes:
      - ~/.cache/yarn:/root/.cache/yarn
      - ./:/usr/share/app
    links:
      - loggly-dummy
      - localstack
    env_file: config.env
    environment:
      CONFIG: |
        {
          "groups": [
            {
              "match": "^ecs\\-",
              "strategy": "ecs",
              "tags": [
                "ecs",
                "cloudwatch2loggly"
              ]
            },
            {
              "match": "^\\/aws\\/lambda\\/",
              "strategy": "lambda",
              "tags": [
                "lambda",
                "cloudwatch2loggly"
              ]
            },
            {
              "match": ".*",
              "strategy": "default",
              "tags": [
                "cloudwatch2loggly"
              ]
            }
          ],
          "subscription": {
            "whitelist": [
              "^\\/aws\\/lambda\\/"
            ]
          }
        }

  loggly-dummy:
    build: .docker/loggly-dummy
    volumes:
      - .docker/loggly-dummy/data/:/usr/share/app/data
    ports:
      - 80

  # this wont work and is just a precaution to not accidentally hit real AWS resources
  localstack:
    image: localstack/localstack
    ports:
      - 4582
    environment:
      SERVICES: 'cloudwatch'
      DEFAULT_REGION: eu-west-1
